### ISSUE TITLE
Trouble installing node-chipolo on Mac

### ISSUE THREAD

**Issue by kshrujan** [sandeepmistry/node-chipolo#6]
I've been having trouble installing the library on my Mac. I end up getting the following errors upon install:

<img width="664" alt="screen shot 2017-01-03 at 8 47 14 pm" src="https://cloud.githubusercontent.com/assets/13262766/21631956/e7d3b7f0-d1f5-11e6-8f46-b7b9b77db3d0.png">

![image](https://cloud.githubusercontent.com/assets/13262766/21628747/988f6820-d1d6-11e6-943e-2ba34716c114.png)

Also, here is the log file: 
[debug.txt](https://github.com/sandeepmistry/node-chipolo/files/683654/debug.txt)

I looked at the prerequisites for noble installation on Mac, and it appears it only needs XCode, which I have already. Any help would be appreciated.

**Comment by sandeepmistry** [comment]
@kshrujan this module is using a really really really old version of noble.

I would suggestion you update `package.json` to use `^1.7.0` then run `npm install` again. If this works please submit a pull request.

**Comment by ninth-mind** [comment]
submitted pull request

**Comment by sandeepmistry** [comment]
Closed via #7 which @ninth-mind submitted.
